[project]
name = "my-tools"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "kureta", email = "skureta@gmail.com" }]
requires-python = ">=3.9"
dependencies = [
  "librosa>=0.11.0",
  "marimo>=0.11.21",
  "matplotlib>=3.9.4",
  "numpy>=2.0.2",
  "polars>=1.25.2",
  "torch>=2.6.0",
  "torchaudio>=2.6.0",
  "torchvision>=0.21.0",
  "watchdog>=6.0.0",
]

[project.scripts]
my-tools = "my_tools:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.marimo.runtime]
output_max_bytes = 100_000_000
