[project]
name = "my-tools"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "kureta", email = "skureta@gmail.com" }]
requires-python = ">=3.9"
dependencies = [
  "librosa>=0.11.0",
  "marimo[lsp]>=0.11.21",
  "matplotlib>=3.9.4",
  "mido>=1.3.3",
  "numpy>=2.0.2",
  "polars>=1.25.2",
  "torch>=2.6.0",
  "torchaudio>=2.6.0",
  "torchvision>=0.21.0",
  "watchdog>=6.0.0",
]

[project.scripts]
my-tools = "my_tools:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.marimo.runtime]
output_max_bytes = 100_000_000

[tool.marimo.experimental]
lsp = true

# Language server configuration
[tool.marimo.language_servers.pylsp]
enabled = true            # Enable/disable the Python language server
enable_mypy = true        # Type checking with mypy (enabled by default, if installed)
enable_ruff = true        # Linting with ruff (enabled by default, if installed)
enable_flake8 = false     # Linting with flake8
enable_pydocstyle = false # Check docstring style
enable_pylint = false     # Linting with pylint
enable_pyflakes = false   # Syntax checking with pyflakes

# Diagnostics configuration
[tool.marimo.diagnostics]
enabled = true # Show diagnostics in the editor
